services:
  
  glpi:
    # -- Testing --
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   no_cache: true
    #   args:
    #     - COOKIE_SECURE=0
    image: glpi/glpi:11
    env_file: .env
    volumes:
    - .:/var/www/glpi/plugins/googlessoauth
    - ./local_define.php:/var/www/glpi/config/local_define.php
    ports:
      - "8080:80"

  db:
    image: mysql:8.4
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${GLPI_DB_NAME:-glpi}
      MYSQL_USER: ${GLPI_DB_USER:-glpi}
      MYSQL_PASSWORD: ${GLPI_DB_PASSWORD:-glpi}

volumes:
  db_data:

networks:
  mysql:
    driver: bridge
      